[package]
name = "icefetch"
version = "0.1.0"
edition = "2021"

[dependencies]
termimage = "1.2.1"
term_size = "0.3"
#DO NOT UPGRADE TO 0.25.1
image = "0.24"
text-splitter = "0.13.3"
colored = "2.1.0"
bytesize = "1.3.0"
